export default (function (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) {
	return {
		tarot: {
			jester: { name: 'Jester', label: '愚者', hebrew: f },
			magus: { name: 'Magus', label: '魔術師', hebrew: g },
			popess: { name: 'Popess', label: '女教皇', hebrew: h },
			empress: { name: 'Empress', label: '女帝', hebrew: i },
			emperor: { name: 'Emperor', label: '皇帝', hebrew: 'צ' },
			pope: { name: 'Pope', label: '教皇', hebrew: j },
			lovers: { name: 'Lovers', label: '恋人', hebrew: 'ז' },
			chariot: { name: 'Chariot', label: '戦車', hebrew: 'ח' },
			justice: { name: 'Justice', label: '正義', hebrew: k },
			hermit: { name: 'Hermit', label: '隠者', hebrew: l },
			wheel: { name: 'Wheel of Fortune', label: '運命の輪', hebrew: m },
			fortitude: { name: 'Fortitude', label: '剛毅', hebrew: 'ט' },
			hanged: { name: 'Hanged Man', label: '吊られ人', hebrew: n },
			death: { name: 'Death', label: '死神', hebrew: 'נ' },
			temperance: { name: 'Temperance', label: '節制', hebrew: o },
			devil: { name: 'Devil', label: '悪魔', hebrew: 'ע' },
			tower: { name: 'Tower', label: '塔', hebrew: p },
			star: { name: 'Star', label: '星', hebrew: q },
			moon: { name: 'Moon', label: r, hebrew: 'ק' },
			sun: { name: 'Sun', label: s, hebrew: 'ר' },
			judgement: { name: 'Judgement', label: '審判', hebrew: 'ש' },
			world: { name: 'World', label: '世界', hebrew: 'ת' }
		},
		zodiac: {
			Aries: { types: [a], symbol: '♈', label: '白羊宮', hebrew: p, ratio: 441.395 },
			Taurus: { types: [a], symbol: '♉', label: '金牛宮', hebrew: f, ratio: 797.249 },
			Gemini: { types: [a], symbol: '♊️', label: '双児宮', hebrew: g, ratio: 513.761 },
			Cancer: {
				types: [a],
				name: 'Cancer',
				symbol: '♋️',
				label: '巨蟹宮',
				hebrew: h,
				ratio: 505.872
			},
			Leo: { types: [a], symbol: '♌', label: '獅子宮', hebrew: i, ratio: 946.964 },
			Virgo: { types: [a], symbol: '️♍️', label: '処女宮', hebrew: q, ratio: 1294.428 },
			Libra: { types: [a], symbol: '♎️', label: '天秤宮', hebrew: j, ratio: 538.052 },
			Scorpius: { types: [a], symbol: '♏️', label: '天蝎宮', hebrew: l },
			Sagittarius: { types: [a], symbol: '♐️', label: '人馬宮', hebrew: m, ratio: 867.432 },
			Capricorn: {
				types: [a],
				name: 'Capricorn',
				symbol: '♑️',
				label: '磨羯宮',
				hebrew: k,
				ratio: 497.783
			},
			Aquarius: { types: [a], symbol: '♒️', label: '宝瓶宮', hebrew: n, ratio: 979.854 },
			Pisces: { types: [a], symbol: '♓️', label: '双魚宮', hebrew: o, ratio: 889.417 },
			Ophiuchus: { types: [a], symbol: '⛎', label: '蛇遣座', hebrew: '', ratio: 948.34 }
		},
		Ptolemaic: {
			Andromeda: { types: [a], label: 'アンドロメダ座', ratio: 722.278 },
			Aquila: { types: [a], label: '鷲座', ratio: 652.473 },
			Ara: { types: [a], label: '祭壇座', ratio: 237.057 },
			Auriga: { types: [a], label: '御者座', ratio: 657.438 },
			Bootes: { types: [a], label: '牛飼座', ratio: 906.831 },
			'Canis Major': { types: [a], label: '大犬座', ratio: 380.118 },
			'Canis Minor': { types: [a], label: '小犬座', ratio: 183.367 },
			Cassiopeia: { types: [a], label: 'カシオペヤ座', ratio: 598.407 },
			Centaurus: { types: [a], label: 'ケンタウルス座', ratio: 1060.422 },
			Cepheus: { types: [a], label: 'ケフェウス座', ratio: 587.787 },
			Cetus: { types: [a], label: '鯨座', ratio: 1231.411 },
			'Corona Australis': { types: [a], label: '南の冠座', ratio: 127.696 },
			'Corona Borealis': { types: [a], label: '冠座', ratio: 178.71 },
			Corvus: { types: [a], label: '烏座', ratio: 183.801 },
			Crater: { types: [a], label: '杯座', ratio: 282.398 },
			Cygnus: { types: [a], label: '白鳥座', ratio: 803.983 },
			Delphinus: { types: [a], label: 'イルカ座', ratio: 188.549 },
			Draco: { types: [a], label: '竜座', ratio: 1082.952 },
			Equuleus: { types: [a], label: '仔馬座', ratio: 71.641 },
			Eridanus: { types: [a], label: 'エリダヌス座', ratio: 1137.919 },
			Hercules: { types: [a], label: 'ヘラクレス座', ratio: 1225.148 },
			Hydra: { types: [a], label: '海蛇座', ratio: 1302.844 },
			Lepus: { types: [a], label: '兎座', ratio: 290.291 },
			Lupus: { types: [a], label: '狼座', ratio: 333.683 },
			Lyra: { types: [a], label: '琴座', ratio: 286.476 },
			Orion: { types: [a], label: 'オリオン座', ratio: 594.997 },
			Pegasus: { types: [a], label: 'ペガスス座', ratio: 1120.794 },
			Perseus: { types: [a], label: 'ペルセウス座', ratio: 614.997 },
			'Piscis Austrinus': { types: [a], label: '南の魚座', ratio: 245.375 },
			Sagitta: { types: [a], label: '矢座', ratio: 79.932 },
			Serpens: { types: [a], label: '蛇座', ratio: 636.928 },
			Triangulum: { types: [a], label: '三角座', ratio: 131.847 },
			'Ursa Major': { types: [a], label: '大熊座', ratio: 1279.66 },
			'Ursa Minor': { types: [a], label: '小熊座', ratio: 255.864 }
		},
		Lacaille: {
			Antlia: { types: [a], label: 'ポンプ座', ratio: 238.901 },
			Caelum: { types: [a], label: '彫刻具座', ratio: 124.865 },
			Carina: { types: [a], label: '竜骨座', ratio: 494.184 },
			Circinus: { types: [a], label: 'コンパス座', ratio: 93.353 },
			Fornax: { types: [a], label: '炉座', ratio: 397.502 },
			Horologium: { types: [a], label: '時計座', ratio: 248.885 },
			Mensa: { types: [a], label: 'テーブル山座', ratio: 153.484 },
			Microscopium: { types: [a], label: '顕微鏡座', ratio: 209.513 },
			Norma: { types: [a], label: '定規座', ratio: 165.29 },
			Octans: { types: [a], label: '八分儀座', ratio: 291.045 },
			Pictor: { types: [a], label: '画架座', ratio: 246.739 },
			Puppis: { types: [a], label: '艫座', ratio: 673.434 },
			Pyxis: { types: [a], label: '羅針盤座', ratio: 220.833 },
			Reticulum: { types: [a], label: 'レチクル座', ratio: 113.936 },
			Sculptor: { types: [a], label: '彫刻室座', ratio: 474.764 },
			Telescopium: { types: [a], label: '望遠鏡座', ratio: 251.512 },
			Vela: { types: [a], label: '帆座', ratio: 499.649 }
		},
		Bayer: {
			Apus: { types: [a], label: '風鳥座', ratio: 206.327 },
			Chamaeleon: { types: [a], label: 'カメレオン座', ratio: 131.592 },
			'Coma Berenices': { types: [a], label: '髪の毛座', ratio: 386.475 },
			Dorado: { types: [a], label: '旗魚座', ratio: 179.173 },
			Grus: { types: [a], label: '鶴座', ratio: 365.513 },
			Hydrus: { types: [a], label: '水蛇座', ratio: 243.035 },
			Indus: { types: [a], label: 'インディアン座', ratio: 294.006 },
			Musca: { types: [a], label: '蝿座', ratio: 138.355 },
			Pavo: { types: [a], label: '孔雀座', ratio: 377.666 },
			Phoenix: { types: [a], label: '鳳凰座', ratio: 469.319 },
			'Triangulum Australe': { types: [a], label: '南の三角座', ratio: 109.978 },
			Tucana: { types: [a], label: '巨嘴鳥座', ratio: 294.557 },
			Volans: { types: [a], label: '飛魚座', ratio: 141.354 }
		},
		Plancius: {
			Camelopardalis: { types: [a], label: '長頸鹿座', ratio: 756.828 },
			Columba: { types: [a], label: '鳩座', ratio: 270.184 },
			Crux: { types: [a], label: '南十字座', ratio: 68.447 },
			Monoceros: { types: [a], label: '一角獣座', ratio: 481.569 }
		},
		Hevelius: {
			'Canes Venatici': { types: [a], label: '猟犬座', ratio: 465.194 },
			Lacerta: { types: [a], label: '蜥蜴座', ratio: 200.688 },
			'Leo Minor': { types: [a], label: '小獅子座', ratio: 231.956 },
			Lynx: { types: [a], label: '山猫座', ratio: 545.386 },
			Scutum: { types: [a], label: '盾座', ratio: 109.114 },
			Sextans: { types: [a], label: '六分儀座', ratio: 313.515 },
			Vulpecula: { types: [a], label: '小狐座', ratio: 268.165 }
		},
		planet: {
			sun: { symbol: '☉', label: s },
			mercury: { symbol: '☿', label: '水星' },
			venus: { symbol: '♀', label: '金星' },
			earth: { symbol: '🜨', label: '地球' },
			moon: { symbol: '☾', label: r },
			mars: { symbol: '♂', label: '火星' },
			jupiter: { symbol: '♃', label: '木星' },
			saturn: { symbol: '♄', label: '土星' },
			uranus: { symbol: '⛢', label: '天王星' },
			neptune: { symbol: '♆', label: '海王星' },
			pluto: { symbol: '♇', label: '冥王星' },
			ceres: { symbol: '⚳', label: 'ケレス' },
			pallas: { symbol: '⚴', label: 'パラス' },
			juno: { symbol: '⚵', label: 'ジュノー' },
			vesta: { symbol: '⚶', label: 'ヴェスタ' },
			chiron: { symbol: '⚷', label: 'キロン' },
			lilith: { symbol: '⚸', label: 'リリス' },
			dragonhead: { symbol: '☊', label: '羅睺' },
			dragontail: { symbol: '☋', label: '計都' },
			comet: { symbol: '☄', label: '彗星' }
		},
		shogi: {
			王: { ratio: b, label: '王将' },
			玉: { ratio: b, label: '玉将' },
			飛: { ratio: c, label: '飛車', back: '龍王' },
			角: { ratio: c, label: '角行', back: '竜馬' },
			金: { ratio: e, label: '金将' },
			銀: { ratio: e, label: '銀将', back: '金' },
			香: { ratio: e, label: '香車', back: '杏' },
			桂: { ratio: e, label: '桂馬', back: '圭' },
			歩: { ratio: 16, label: '歩兵', back: 'と' }
		},
		chess: {
			'White King': { ratio: b, symbol: '♔', label: '白王' },
			'White Queen': { ratio: b, symbol: '♕', label: '白妃' },
			'White Rook': { ratio: c, symbol: '♖', label: '白塔' },
			'White Bishop': { ratio: c, symbol: '♗', label: '白僧' },
			'White Knight': { ratio: c, symbol: '♘', label: '白騎' },
			'White Pawn': { ratio: d, symbol: '♙', label: '白兵' },
			'Black King': { ratio: b, symbol: '♚', label: '黒王' },
			'Black Queen': { ratio: b, symbol: '♛', label: '黒妃' },
			'Black Rook': { ratio: c, symbol: '♜', label: '黒塔' },
			'Black Bishop': { ratio: c, symbol: '♝', label: '黒僧' },
			'Black Knight': { ratio: c, symbol: '♞', label: '黒騎' },
			'Black Pawn': { ratio: d, symbol: '♟', label: '黒兵' }
		},
		weather: {
			fine: { ratio: d, symbol: '☀', label: '晴天' },
			partly: { ratio: d, symbol: '🌤️', label: '曇晴' },
			cloudy: { ratio: d, symbol: '☁', label: '曇天' },
			fog: { ratio: b, symbol: '🌁', label: '霧中' },
			rainy: { ratio: d, symbol: '☂', label: '降雨' },
			outrain: { ratio: d, symbol: '🌂', label: '雨後' },
			shower: { ratio: d, symbol: '☔', label: '俄雨' },
			thunder: { ratio: b, symbol: '⚡', label: '落雷' },
			twister: { ratio: b, symbol: '🌪', label: '竜巻' },
			thunderstorm: { ratio: b, symbol: '⛈️', label: '雷雨' },
			rainbow: { ratio: c, symbol: '🌈', label: '虹天' }
		},
		coin: {
			front: { ratio: t, label: '表' },
			back: { ratio: t, label: '裏' },
			stand: { ratio: b, label: '立った' }
		},
		eto10: {
			甲: { name: 'きのえ' },
			乙: { name: 'きのと' },
			丙: { name: 'ひのえ' },
			丁: { name: 'ひのと' },
			戊: { name: 'つちのえ' },
			己: { name: 'つちのと' },
			庚: { name: 'かのえ' },
			辛: { name: 'かのと' },
			壬: { name: 'みずのえ' },
			癸: { name: 'みずのと' }
		},
		eto12: {
			子: { name: 'ね' },
			丑: { name: 'うし' },
			寅: { name: 'とら' },
			卯: { name: 'う' },
			辰: { name: 'たつ' },
			巳: { name: 'み' },
			午: { name: 'うま' },
			未: { name: 'ひつじ' },
			申: { name: 'さる' },
			酉: { name: 'とり' },
			戌: { name: 'いぬ' },
			亥: { name: 'い' }
		}
	};
})(
	'IAU',
	1,
	2,
	8,
	4,
	'א',
	'ב',
	'ג',
	'ד',
	'ו',
	'ל',
	'י',
	'כ',
	'מ',
	'ס',
	'פ',
	'ה',
	'月',
	'太陽',
	500
);
